-- Motodo platform RLS/RPC test scenarios (Phase 1 foundation).
-- Not executed by npm test. Run later against a dedicated Supabase branch with test users.
-- Do not run against production.
--
-- A. Buyer
--    - SELECT active public listings (including is_demo showcase rows)
--    - cannot UPDATE another profile
--    - cannot UPDATE another seller's listing
--    - create_order on a real (is_demo=false) in-stock listing succeeds
--    - create_order with qty > available raises INSUFFICIENT_STOCK
--    - create_order on is_demo listing raises DEMO_LISTING_NOT_FOR_SALE
--    - cannot UPDATE orders rows (RPC only)
--    - start_conversation / send_message only as participant
--    - create_review only on own completed order
--
-- B. Seller
--    - UPDATE own listings
--    - cannot UPDATE another seller's listings
--    - UPDATE quantity below reserved raises QUANTITY_BELOW_RESERVED
--    - approve_seller_profile raises FORBIDDEN
--
-- C. Admin
--    - approve_seller_profile / reject_seller_profile succeed
--    - complete_order still requires confirmed status (INVALID_ORDER_STATE otherwise)
--
-- D. Concurrency
--    - two create_order calls on last unit: one INSUFFICIENT_STOCK (listing row lock)
--
-- E. Notifications
--    - cannot UPDATE another user's notifications
--    - mark_notification_read on someone else's id raises NOTIFICATION_NOT_FOUND
--
-- F. Favorites
--    - toggle_favorite on active/sold/demo listing succeeds
--    - duplicate unique(user_id, listing_id) / second toggle unfavorites
--    - cannot SELECT another user's favorites
--    - draft listing of another seller → LISTING_NOT_FOUND
--
-- G. Cart
--    - add_to_cart on eligible listing succeeds and does not change listing.quantity or create orders
--    - second add_to_cart returns the same row (no duplicate)
--    - add_to_cart on is_demo → DEMO_LISTING_NOT_FOR_SALE
--    - add_to_cart on own listing → SELF_PURCHASE
--    - add_to_cart when available < 1 → INSUFFICIENT_STOCK
--    - update_cart_quantity < 1 → INVALID_QUANTITY
--    - update_cart_quantity > available → INSUFFICIENT_STOCK
--    - cannot SELECT another user's cart_items
--    - direct INSERT/UPDATE/DELETE on cart_items denied (RPC only)
--    - clear_cart deletes only auth.uid() rows
--    - stale sold listing remains selectable; is_available = false
--
-- Expected Motodo codes (details/hint and "CODE: " message prefix):
-- UNAUTHORIZED, FORBIDDEN, LISTING_NOT_FOUND, LISTING_UNAVAILABLE, INSUFFICIENT_STOCK,
-- DEMO_LISTING_NOT_FOR_SALE, QUANTITY_BELOW_RESERVED, INVALID_ORDER_STATE, ORDER_NOT_FOUND,
-- SELF_CONVERSATION, CONVERSATION_NOT_FOUND, MESSAGE_NOT_ALLOWED, REVIEW_NOT_ALLOWED,
-- NOTIFICATION_NOT_FOUND, SELLER_NOT_APPROVED, CART_ITEM_NOT_FOUND, INVALID_QUANTITY,
-- SELF_PURCHASE.
